### ISSUE TITLE
Strict Dep Pinning

### ISSUE THREAD

**Issue by aaronclong** [dolthub/doltpy#185]
`doltpy` has very strict deps pinning which makes it hard to combine with other libraries. Can ranges be provided here?

![Screenshot from 2023-01-08 11-27-00](https://user-images.githubusercontent.com/7354981/211207876-9d9f6d54-f2de-4ad3-9751-43cc8eba82bb.png)

**Comment by fulghum** [comment]
Hey @aaronclong, thanks for checking out Dolt! 

We deprecated the `doltpy` project last year and have started encouraging people to use the standard Python MySQL tools to work with Dolt from Python instead. The rational is that the `dolt sql-server` is now a solid and stable option for accessing Dolt databases now, and we think it makes more sense for people to use the standard MySQL tools with Dolt instead of us providing a custom Python layer. That also means we can keep our focus on the core Dolt features that help users across all languages. 

If you want to drop by the [DoltHub Discord server](https://discord.com/invite/RFwfYpu), we'd be more than happy to chat more about your specific use case or discuss how to use other Python tooling to make accessing Dolt databases easy. 

And last, but not least... if you really like `doltpy`, then you of course also have the option to fork the repo and make any changes you need for your use. 

Hope that makes sense. Don't be shy to engage us more here or on Discord if we can help you in any way at all with your work with Dolt.

**Comment by aaronclong** [comment]
Thanks for letting me know, I'll check that out.

**Comment by fulghum** [comment]
Thanks @aaronclong. I'll close this issue, but please feel free to reopen or ping us on Discord if you're having any trouble at all getting things working like you need!
